// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: azpb.proto

package authz

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Checker_UserList_FullMethodName                    = "/azpb.Checker/UserList"
	Checker_User_FullMethodName                        = "/azpb.Checker/User"
	Checker_Me_FullMethodName                          = "/azpb.Checker/Me"
	Checker_TenantList_FullMethodName                  = "/azpb.Checker/TenantList"
	Checker_Tenant_FullMethodName                      = "/azpb.Checker/Tenant"
	Checker_TenantPermissions_FullMethodName           = "/azpb.Checker/TenantPermissions"
	Checker_TenantSave_FullMethodName                  = "/azpb.Checker/TenantSave"
	Checker_TenantAddPermission_FullMethodName         = "/azpb.Checker/TenantAddPermission"
	Checker_TenantRemovePermission_FullMethodName      = "/azpb.Checker/TenantRemovePermission"
	Checker_TenantCreate_FullMethodName                = "/azpb.Checker/TenantCreate"
	Checker_TenantCreateGroup_FullMethodName           = "/azpb.Checker/TenantCreateGroup"
	Checker_GroupList_FullMethodName                   = "/azpb.Checker/GroupList"
	Checker_Group_FullMethodName                       = "/azpb.Checker/Group"
	Checker_GroupPermissions_FullMethodName            = "/azpb.Checker/GroupPermissions"
	Checker_GroupSave_FullMethodName                   = "/azpb.Checker/GroupSave"
	Checker_GroupAddPermission_FullMethodName          = "/azpb.Checker/GroupAddPermission"
	Checker_GroupRemovePermission_FullMethodName       = "/azpb.Checker/GroupRemovePermission"
	Checker_GroupSetTenant_FullMethodName              = "/azpb.Checker/GroupSetTenant"
	Checker_FeedList_FullMethodName                    = "/azpb.Checker/FeedList"
	Checker_Feed_FullMethodName                        = "/azpb.Checker/Feed"
	Checker_FeedPermissions_FullMethodName             = "/azpb.Checker/FeedPermissions"
	Checker_FeedSetGroup_FullMethodName                = "/azpb.Checker/FeedSetGroup"
	Checker_FeedVersionList_FullMethodName             = "/azpb.Checker/FeedVersionList"
	Checker_FeedVersion_FullMethodName                 = "/azpb.Checker/FeedVersion"
	Checker_FeedVersionPermissions_FullMethodName      = "/azpb.Checker/FeedVersionPermissions"
	Checker_FeedVersionAddPermission_FullMethodName    = "/azpb.Checker/FeedVersionAddPermission"
	Checker_FeedVersionRemovePermission_FullMethodName = "/azpb.Checker/FeedVersionRemovePermission"
)

// CheckerClient is the client API for Checker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckerClient interface {
	UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	User(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Me(ctx context.Context, in *MeRequest, opts ...grpc.CallOption) (*MeResponse, error)
	TenantList(ctx context.Context, in *TenantListRequest, opts ...grpc.CallOption) (*TenantListResponse, error)
	Tenant(ctx context.Context, in *TenantRequest, opts ...grpc.CallOption) (*TenantResponse, error)
	TenantPermissions(ctx context.Context, in *TenantRequest, opts ...grpc.CallOption) (*TenantPermissionsResponse, error)
	TenantSave(ctx context.Context, in *TenantSaveRequest, opts ...grpc.CallOption) (*TenantSaveResponse, error)
	TenantAddPermission(ctx context.Context, in *TenantModifyPermissionRequest, opts ...grpc.CallOption) (*TenantSaveResponse, error)
	TenantRemovePermission(ctx context.Context, in *TenantModifyPermissionRequest, opts ...grpc.CallOption) (*TenantSaveResponse, error)
	TenantCreate(ctx context.Context, in *TenantCreateRequest, opts ...grpc.CallOption) (*TenantSaveResponse, error)
	TenantCreateGroup(ctx context.Context, in *TenantCreateGroupRequest, opts ...grpc.CallOption) (*GroupSaveResponse, error)
	GroupList(ctx context.Context, in *GroupListRequest, opts ...grpc.CallOption) (*GroupListResponse, error)
	Group(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*GroupResponse, error)
	GroupPermissions(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*GroupPermissionsResponse, error)
	GroupSave(ctx context.Context, in *GroupSaveRequest, opts ...grpc.CallOption) (*GroupSaveResponse, error)
	GroupAddPermission(ctx context.Context, in *GroupModifyPermissionRequest, opts ...grpc.CallOption) (*GroupSaveResponse, error)
	GroupRemovePermission(ctx context.Context, in *GroupModifyPermissionRequest, opts ...grpc.CallOption) (*GroupSaveResponse, error)
	GroupSetTenant(ctx context.Context, in *GroupSetTenantRequest, opts ...grpc.CallOption) (*GroupSetTenantResponse, error)
	FeedList(ctx context.Context, in *FeedListRequest, opts ...grpc.CallOption) (*FeedListResponse, error)
	Feed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error)
	FeedPermissions(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedPermissionsResponse, error)
	FeedSetGroup(ctx context.Context, in *FeedSetGroupRequest, opts ...grpc.CallOption) (*FeedSaveResponse, error)
	FeedVersionList(ctx context.Context, in *FeedVersionListRequest, opts ...grpc.CallOption) (*FeedVersionListResponse, error)
	FeedVersion(ctx context.Context, in *FeedVersionRequest, opts ...grpc.CallOption) (*FeedVersionResponse, error)
	FeedVersionPermissions(ctx context.Context, in *FeedVersionRequest, opts ...grpc.CallOption) (*FeedVersionPermissionsResponse, error)
	FeedVersionAddPermission(ctx context.Context, in *FeedVersionModifyPermissionRequest, opts ...grpc.CallOption) (*FeedVersionSaveResponse, error)
	FeedVersionRemovePermission(ctx context.Context, in *FeedVersionModifyPermissionRequest, opts ...grpc.CallOption) (*FeedVersionSaveResponse, error)
}

type checkerClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckerClient(cc grpc.ClientConnInterface) CheckerClient {
	return &checkerClient{cc}
}

func (c *checkerClient) UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, Checker_UserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) User(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, Checker_User_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) Me(ctx context.Context, in *MeRequest, opts ...grpc.CallOption) (*MeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeResponse)
	err := c.cc.Invoke(ctx, Checker_Me_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) TenantList(ctx context.Context, in *TenantListRequest, opts ...grpc.CallOption) (*TenantListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantListResponse)
	err := c.cc.Invoke(ctx, Checker_TenantList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) Tenant(ctx context.Context, in *TenantRequest, opts ...grpc.CallOption) (*TenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantResponse)
	err := c.cc.Invoke(ctx, Checker_Tenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) TenantPermissions(ctx context.Context, in *TenantRequest, opts ...grpc.CallOption) (*TenantPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantPermissionsResponse)
	err := c.cc.Invoke(ctx, Checker_TenantPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) TenantSave(ctx context.Context, in *TenantSaveRequest, opts ...grpc.CallOption) (*TenantSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantSaveResponse)
	err := c.cc.Invoke(ctx, Checker_TenantSave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) TenantAddPermission(ctx context.Context, in *TenantModifyPermissionRequest, opts ...grpc.CallOption) (*TenantSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantSaveResponse)
	err := c.cc.Invoke(ctx, Checker_TenantAddPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) TenantRemovePermission(ctx context.Context, in *TenantModifyPermissionRequest, opts ...grpc.CallOption) (*TenantSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantSaveResponse)
	err := c.cc.Invoke(ctx, Checker_TenantRemovePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) TenantCreate(ctx context.Context, in *TenantCreateRequest, opts ...grpc.CallOption) (*TenantSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantSaveResponse)
	err := c.cc.Invoke(ctx, Checker_TenantCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) TenantCreateGroup(ctx context.Context, in *TenantCreateGroupRequest, opts ...grpc.CallOption) (*GroupSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupSaveResponse)
	err := c.cc.Invoke(ctx, Checker_TenantCreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) GroupList(ctx context.Context, in *GroupListRequest, opts ...grpc.CallOption) (*GroupListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupListResponse)
	err := c.cc.Invoke(ctx, Checker_GroupList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) Group(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupResponse)
	err := c.cc.Invoke(ctx, Checker_Group_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) GroupPermissions(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*GroupPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupPermissionsResponse)
	err := c.cc.Invoke(ctx, Checker_GroupPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) GroupSave(ctx context.Context, in *GroupSaveRequest, opts ...grpc.CallOption) (*GroupSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupSaveResponse)
	err := c.cc.Invoke(ctx, Checker_GroupSave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) GroupAddPermission(ctx context.Context, in *GroupModifyPermissionRequest, opts ...grpc.CallOption) (*GroupSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupSaveResponse)
	err := c.cc.Invoke(ctx, Checker_GroupAddPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) GroupRemovePermission(ctx context.Context, in *GroupModifyPermissionRequest, opts ...grpc.CallOption) (*GroupSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupSaveResponse)
	err := c.cc.Invoke(ctx, Checker_GroupRemovePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) GroupSetTenant(ctx context.Context, in *GroupSetTenantRequest, opts ...grpc.CallOption) (*GroupSetTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupSetTenantResponse)
	err := c.cc.Invoke(ctx, Checker_GroupSetTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) FeedList(ctx context.Context, in *FeedListRequest, opts ...grpc.CallOption) (*FeedListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedListResponse)
	err := c.cc.Invoke(ctx, Checker_FeedList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) Feed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedResponse)
	err := c.cc.Invoke(ctx, Checker_Feed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) FeedPermissions(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedPermissionsResponse)
	err := c.cc.Invoke(ctx, Checker_FeedPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) FeedSetGroup(ctx context.Context, in *FeedSetGroupRequest, opts ...grpc.CallOption) (*FeedSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedSaveResponse)
	err := c.cc.Invoke(ctx, Checker_FeedSetGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) FeedVersionList(ctx context.Context, in *FeedVersionListRequest, opts ...grpc.CallOption) (*FeedVersionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedVersionListResponse)
	err := c.cc.Invoke(ctx, Checker_FeedVersionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) FeedVersion(ctx context.Context, in *FeedVersionRequest, opts ...grpc.CallOption) (*FeedVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedVersionResponse)
	err := c.cc.Invoke(ctx, Checker_FeedVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) FeedVersionPermissions(ctx context.Context, in *FeedVersionRequest, opts ...grpc.CallOption) (*FeedVersionPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedVersionPermissionsResponse)
	err := c.cc.Invoke(ctx, Checker_FeedVersionPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) FeedVersionAddPermission(ctx context.Context, in *FeedVersionModifyPermissionRequest, opts ...grpc.CallOption) (*FeedVersionSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedVersionSaveResponse)
	err := c.cc.Invoke(ctx, Checker_FeedVersionAddPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerClient) FeedVersionRemovePermission(ctx context.Context, in *FeedVersionModifyPermissionRequest, opts ...grpc.CallOption) (*FeedVersionSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedVersionSaveResponse)
	err := c.cc.Invoke(ctx, Checker_FeedVersionRemovePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckerServer is the server API for Checker service.
// All implementations must embed UnimplementedCheckerServer
// for forward compatibility.
type CheckerServer interface {
	UserList(context.Context, *UserListRequest) (*UserListResponse, error)
	User(context.Context, *UserRequest) (*UserResponse, error)
	Me(context.Context, *MeRequest) (*MeResponse, error)
	TenantList(context.Context, *TenantListRequest) (*TenantListResponse, error)
	Tenant(context.Context, *TenantRequest) (*TenantResponse, error)
	TenantPermissions(context.Context, *TenantRequest) (*TenantPermissionsResponse, error)
	TenantSave(context.Context, *TenantSaveRequest) (*TenantSaveResponse, error)
	TenantAddPermission(context.Context, *TenantModifyPermissionRequest) (*TenantSaveResponse, error)
	TenantRemovePermission(context.Context, *TenantModifyPermissionRequest) (*TenantSaveResponse, error)
	TenantCreate(context.Context, *TenantCreateRequest) (*TenantSaveResponse, error)
	TenantCreateGroup(context.Context, *TenantCreateGroupRequest) (*GroupSaveResponse, error)
	GroupList(context.Context, *GroupListRequest) (*GroupListResponse, error)
	Group(context.Context, *GroupRequest) (*GroupResponse, error)
	GroupPermissions(context.Context, *GroupRequest) (*GroupPermissionsResponse, error)
	GroupSave(context.Context, *GroupSaveRequest) (*GroupSaveResponse, error)
	GroupAddPermission(context.Context, *GroupModifyPermissionRequest) (*GroupSaveResponse, error)
	GroupRemovePermission(context.Context, *GroupModifyPermissionRequest) (*GroupSaveResponse, error)
	GroupSetTenant(context.Context, *GroupSetTenantRequest) (*GroupSetTenantResponse, error)
	FeedList(context.Context, *FeedListRequest) (*FeedListResponse, error)
	Feed(context.Context, *FeedRequest) (*FeedResponse, error)
	FeedPermissions(context.Context, *FeedRequest) (*FeedPermissionsResponse, error)
	FeedSetGroup(context.Context, *FeedSetGroupRequest) (*FeedSaveResponse, error)
	FeedVersionList(context.Context, *FeedVersionListRequest) (*FeedVersionListResponse, error)
	FeedVersion(context.Context, *FeedVersionRequest) (*FeedVersionResponse, error)
	FeedVersionPermissions(context.Context, *FeedVersionRequest) (*FeedVersionPermissionsResponse, error)
	FeedVersionAddPermission(context.Context, *FeedVersionModifyPermissionRequest) (*FeedVersionSaveResponse, error)
	FeedVersionRemovePermission(context.Context, *FeedVersionModifyPermissionRequest) (*FeedVersionSaveResponse, error)
	mustEmbedUnimplementedCheckerServer()
}

// UnimplementedCheckerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckerServer struct{}

func (UnimplementedCheckerServer) UserList(context.Context, *UserListRequest) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserList not implemented")
}
func (UnimplementedCheckerServer) User(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User not implemented")
}
func (UnimplementedCheckerServer) Me(context.Context, *MeRequest) (*MeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Me not implemented")
}
func (UnimplementedCheckerServer) TenantList(context.Context, *TenantListRequest) (*TenantListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantList not implemented")
}
func (UnimplementedCheckerServer) Tenant(context.Context, *TenantRequest) (*TenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tenant not implemented")
}
func (UnimplementedCheckerServer) TenantPermissions(context.Context, *TenantRequest) (*TenantPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantPermissions not implemented")
}
func (UnimplementedCheckerServer) TenantSave(context.Context, *TenantSaveRequest) (*TenantSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantSave not implemented")
}
func (UnimplementedCheckerServer) TenantAddPermission(context.Context, *TenantModifyPermissionRequest) (*TenantSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantAddPermission not implemented")
}
func (UnimplementedCheckerServer) TenantRemovePermission(context.Context, *TenantModifyPermissionRequest) (*TenantSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantRemovePermission not implemented")
}
func (UnimplementedCheckerServer) TenantCreate(context.Context, *TenantCreateRequest) (*TenantSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantCreate not implemented")
}
func (UnimplementedCheckerServer) TenantCreateGroup(context.Context, *TenantCreateGroupRequest) (*GroupSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TenantCreateGroup not implemented")
}
func (UnimplementedCheckerServer) GroupList(context.Context, *GroupListRequest) (*GroupListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupList not implemented")
}
func (UnimplementedCheckerServer) Group(context.Context, *GroupRequest) (*GroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Group not implemented")
}
func (UnimplementedCheckerServer) GroupPermissions(context.Context, *GroupRequest) (*GroupPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupPermissions not implemented")
}
func (UnimplementedCheckerServer) GroupSave(context.Context, *GroupSaveRequest) (*GroupSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupSave not implemented")
}
func (UnimplementedCheckerServer) GroupAddPermission(context.Context, *GroupModifyPermissionRequest) (*GroupSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupAddPermission not implemented")
}
func (UnimplementedCheckerServer) GroupRemovePermission(context.Context, *GroupModifyPermissionRequest) (*GroupSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupRemovePermission not implemented")
}
func (UnimplementedCheckerServer) GroupSetTenant(context.Context, *GroupSetTenantRequest) (*GroupSetTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupSetTenant not implemented")
}
func (UnimplementedCheckerServer) FeedList(context.Context, *FeedListRequest) (*FeedListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedList not implemented")
}
func (UnimplementedCheckerServer) Feed(context.Context, *FeedRequest) (*FeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Feed not implemented")
}
func (UnimplementedCheckerServer) FeedPermissions(context.Context, *FeedRequest) (*FeedPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedPermissions not implemented")
}
func (UnimplementedCheckerServer) FeedSetGroup(context.Context, *FeedSetGroupRequest) (*FeedSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedSetGroup not implemented")
}
func (UnimplementedCheckerServer) FeedVersionList(context.Context, *FeedVersionListRequest) (*FeedVersionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedVersionList not implemented")
}
func (UnimplementedCheckerServer) FeedVersion(context.Context, *FeedVersionRequest) (*FeedVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedVersion not implemented")
}
func (UnimplementedCheckerServer) FeedVersionPermissions(context.Context, *FeedVersionRequest) (*FeedVersionPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedVersionPermissions not implemented")
}
func (UnimplementedCheckerServer) FeedVersionAddPermission(context.Context, *FeedVersionModifyPermissionRequest) (*FeedVersionSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedVersionAddPermission not implemented")
}
func (UnimplementedCheckerServer) FeedVersionRemovePermission(context.Context, *FeedVersionModifyPermissionRequest) (*FeedVersionSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedVersionRemovePermission not implemented")
}
func (UnimplementedCheckerServer) mustEmbedUnimplementedCheckerServer() {}
func (UnimplementedCheckerServer) testEmbeddedByValue()                 {}

// UnsafeCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckerServer will
// result in compilation errors.
type UnsafeCheckerServer interface {
	mustEmbedUnimplementedCheckerServer()
}

func RegisterCheckerServer(s grpc.ServiceRegistrar, srv CheckerServer) {
	// If the following call pancis, it indicates UnimplementedCheckerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Checker_ServiceDesc, srv)
}

func _Checker_UserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).UserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_UserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).UserList(ctx, req.(*UserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_User_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).User(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_User_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).User(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_Me_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).Me(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_Me_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).Me(ctx, req.(*MeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_TenantList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).TenantList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_TenantList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).TenantList(ctx, req.(*TenantListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_Tenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).Tenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_Tenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).Tenant(ctx, req.(*TenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_TenantPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).TenantPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_TenantPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).TenantPermissions(ctx, req.(*TenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_TenantSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).TenantSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_TenantSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).TenantSave(ctx, req.(*TenantSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_TenantAddPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantModifyPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).TenantAddPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_TenantAddPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).TenantAddPermission(ctx, req.(*TenantModifyPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_TenantRemovePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantModifyPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).TenantRemovePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_TenantRemovePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).TenantRemovePermission(ctx, req.(*TenantModifyPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_TenantCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).TenantCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_TenantCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).TenantCreate(ctx, req.(*TenantCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_TenantCreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantCreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).TenantCreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_TenantCreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).TenantCreateGroup(ctx, req.(*TenantCreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_GroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).GroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_GroupList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).GroupList(ctx, req.(*GroupListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_Group_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).Group(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_Group_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).Group(ctx, req.(*GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_GroupPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).GroupPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_GroupPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).GroupPermissions(ctx, req.(*GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_GroupSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).GroupSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_GroupSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).GroupSave(ctx, req.(*GroupSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_GroupAddPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupModifyPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).GroupAddPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_GroupAddPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).GroupAddPermission(ctx, req.(*GroupModifyPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_GroupRemovePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupModifyPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).GroupRemovePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_GroupRemovePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).GroupRemovePermission(ctx, req.(*GroupModifyPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_GroupSetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupSetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).GroupSetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_GroupSetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).GroupSetTenant(ctx, req.(*GroupSetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_FeedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).FeedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_FeedList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).FeedList(ctx, req.(*FeedListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_Feed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).Feed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_Feed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).Feed(ctx, req.(*FeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_FeedPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).FeedPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_FeedPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).FeedPermissions(ctx, req.(*FeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_FeedSetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedSetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).FeedSetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_FeedSetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).FeedSetGroup(ctx, req.(*FeedSetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_FeedVersionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedVersionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).FeedVersionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_FeedVersionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).FeedVersionList(ctx, req.(*FeedVersionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_FeedVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).FeedVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_FeedVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).FeedVersion(ctx, req.(*FeedVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_FeedVersionPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).FeedVersionPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_FeedVersionPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).FeedVersionPermissions(ctx, req.(*FeedVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_FeedVersionAddPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedVersionModifyPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).FeedVersionAddPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_FeedVersionAddPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).FeedVersionAddPermission(ctx, req.(*FeedVersionModifyPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Checker_FeedVersionRemovePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedVersionModifyPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServer).FeedVersionRemovePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Checker_FeedVersionRemovePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServer).FeedVersionRemovePermission(ctx, req.(*FeedVersionModifyPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Checker_ServiceDesc is the grpc.ServiceDesc for Checker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Checker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "azpb.Checker",
	HandlerType: (*CheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserList",
			Handler:    _Checker_UserList_Handler,
		},
		{
			MethodName: "User",
			Handler:    _Checker_User_Handler,
		},
		{
			MethodName: "Me",
			Handler:    _Checker_Me_Handler,
		},
		{
			MethodName: "TenantList",
			Handler:    _Checker_TenantList_Handler,
		},
		{
			MethodName: "Tenant",
			Handler:    _Checker_Tenant_Handler,
		},
		{
			MethodName: "TenantPermissions",
			Handler:    _Checker_TenantPermissions_Handler,
		},
		{
			MethodName: "TenantSave",
			Handler:    _Checker_TenantSave_Handler,
		},
		{
			MethodName: "TenantAddPermission",
			Handler:    _Checker_TenantAddPermission_Handler,
		},
		{
			MethodName: "TenantRemovePermission",
			Handler:    _Checker_TenantRemovePermission_Handler,
		},
		{
			MethodName: "TenantCreate",
			Handler:    _Checker_TenantCreate_Handler,
		},
		{
			MethodName: "TenantCreateGroup",
			Handler:    _Checker_TenantCreateGroup_Handler,
		},
		{
			MethodName: "GroupList",
			Handler:    _Checker_GroupList_Handler,
		},
		{
			MethodName: "Group",
			Handler:    _Checker_Group_Handler,
		},
		{
			MethodName: "GroupPermissions",
			Handler:    _Checker_GroupPermissions_Handler,
		},
		{
			MethodName: "GroupSave",
			Handler:    _Checker_GroupSave_Handler,
		},
		{
			MethodName: "GroupAddPermission",
			Handler:    _Checker_GroupAddPermission_Handler,
		},
		{
			MethodName: "GroupRemovePermission",
			Handler:    _Checker_GroupRemovePermission_Handler,
		},
		{
			MethodName: "GroupSetTenant",
			Handler:    _Checker_GroupSetTenant_Handler,
		},
		{
			MethodName: "FeedList",
			Handler:    _Checker_FeedList_Handler,
		},
		{
			MethodName: "Feed",
			Handler:    _Checker_Feed_Handler,
		},
		{
			MethodName: "FeedPermissions",
			Handler:    _Checker_FeedPermissions_Handler,
		},
		{
			MethodName: "FeedSetGroup",
			Handler:    _Checker_FeedSetGroup_Handler,
		},
		{
			MethodName: "FeedVersionList",
			Handler:    _Checker_FeedVersionList_Handler,
		},
		{
			MethodName: "FeedVersion",
			Handler:    _Checker_FeedVersion_Handler,
		},
		{
			MethodName: "FeedVersionPermissions",
			Handler:    _Checker_FeedVersionPermissions_Handler,
		},
		{
			MethodName: "FeedVersionAddPermission",
			Handler:    _Checker_FeedVersionAddPermission_Handler,
		},
		{
			MethodName: "FeedVersionRemovePermission",
			Handler:    _Checker_FeedVersionRemovePermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "azpb.proto",
}
