fragment alert on Alert {
  cause
  effect
  severity_level
  url {
    language
    text
  }
  header_text {
    language
    text
  }
  description_text {
    language
    text
  }
  tts_header_text {
    language
    text
  }
  tts_description_text {
    language
    text
  }
  active_period {
    start
    end
  }
}

query ($limit: Int, $ids: [Int!], $after: Int, $include_alerts: Boolean!, $include_routes: Boolean!, $where: AgencyFilter) {
  agencies(limit: $limit, after: $after, ids: $ids, where: $where) {
    id
    agency_name
    agency_id
    onestop_id
    agency_url
    agency_timezone
    agency_lang
    agency_phone
    agency_fare_url
    agency_email
    geometry
    operator {
      onestop_id
      name
      short_name
      tags
      feeds {
        id
        onestop_id
        name
        spec
      }
    }
    alerts @include(if: $include_alerts) {
      ...alert
    }
    places(where: {min_rank: 0.2}) {
      city_name
      adm0_name
      adm1_name
    }
    feed_version {
      id
      sha1
      fetched_at
      feed {
        id
        onestop_id
      }
    }
    routes(limit: 1000) @include(if: $include_routes) {
      id
      route_id
      route_short_name
      route_long_name
      alerts @include(if: $include_alerts) {
        ...alert
      }
    }
  }
}
