query($limit: Int, $ids: [Int!], $after: Int, $where: FeedFilter) {
	feeds(limit: $limit, ids: $ids, after: $after, where: $where) {
	  id
	  spec
	  name
	  onestop_id
	  languages
	  tags
	  urls {
		static_current
		static_historic
		static_planned
		realtime_vehicle_positions
		realtime_trip_updates
		realtime_alerts
		gbfs_auto_discovery
		mds_provider
	  }
	  license {
		spdx_identifier
		url
		use_without_attribution
		create_derived_product
		redistribution_allowed
		commercial_use_allowed
		share_alike_optional
		attribution_text
		attribution_instructions
	  }
	  authorization {
		  type
		  param_name
		  info_url
	  }
	  feed_state {
		feed_version {
		  id
		  sha1
		  url
		  fetched_at
		  geometry
		  feed_version_gtfs_import {
			id
			in_progress
			success
			exception_log
		  }
		}
	  }
	  feed_versions(limit: 1000) {
		id
		sha1
		fetched_at
		url
		earliest_calendar_date
		latest_calendar_date
	  }
	}
  } 