package enums

type RouteType struct {
	Code     int
	Name     string
	Category string
}

var RouteTypes = []RouteType{
	{Code: 0, Name: "Tram", Category: "rail"},
	{Code: 1, Name: "Metro", Category: "rail"},
	{Code: 2, Name: "Rail", Category: "rail"},
	{Code: 3, Name: "Bus", Category: "bus"},
	{Code: 4, Name: "Ferry", Category: "ferry"},
	{Code: 5, Name: "Cablecar", Category: "rail"},
	{Code: 6, Name: "Gondola", Category: "incline"},
	{Code: 7, Name: "Funicular", Category: "incline"},
	{Code: 100, Name: "Railway Service", Category: "rail"},
	{Code: 101, Name: "High Speed Rail Service", Category: "rail"},
	{Code: 102, Name: "Long Distance Trains", Category: "rail"},
	{Code: 103, Name: "Inter Regional Rail Service", Category: "rail"},
	{Code: 104, Name: "Car Transport Rail Service", Category: "rail"},
	{Code: 105, Name: "Sleeper Rail Service", Category: "rail"},
	{Code: 106, Name: "Regional Rail Service", Category: "rail"},
	{Code: 107, Name: "Tourist Railway Service", Category: "rail"},
	{Code: 108, Name: "Rail Shuttle (Within Complex)", Category: "rail"},
	{Code: 109, Name: "Suburban Railway", Category: "rail"},
	{Code: 110, Name: "Replacement Rail Service", Category: "rail"},
	{Code: 111, Name: "Special Rail Service", Category: "rail"},
	{Code: 112, Name: "Lorry Transport Rail Service", Category: "rail"},
	{Code: 113, Name: "All Rail Services", Category: "rail"},
	{Code: 114, Name: "Cross-Country Rail Service", Category: "rail"},
	{Code: 115, Name: "Vehicle Transport Rail Service", Category: "rail"},
	{Code: 116, Name: "Rack and Pinion Railway", Category: "rail"},
	{Code: 117, Name: "Additional Rail Service", Category: "rail"},
	{Code: 200, Name: "Coach Service", Category: "bus"},
	{Code: 201, Name: "International Coach Service", Category: "bus"},
	{Code: 202, Name: "National Coach Service", Category: "bus"},
	{Code: 203, Name: "Shuttle Coach Service", Category: "bus"},
	{Code: 204, Name: "Regional Coach Service", Category: "bus"},
	{Code: 205, Name: "Special Coach Service", Category: "bus"},
	{Code: 206, Name: "Sightseeing Coach Service", Category: "bus"},
	{Code: 207, Name: "Tourist Coach Service", Category: "bus"},
	{Code: 208, Name: "Commuter Coach Service", Category: "bus"},
	{Code: 209, Name: "All Coach Services", Category: "bus"},
	{Code: 300, Name: "Suburban Railway Service", Category: "rail"},
	{Code: 400, Name: "Urban Railway Service", Category: "rail"},
	{Code: 401, Name: "Metro Service", Category: "rail"},
	{Code: 402, Name: "Underground Service", Category: "rail"},
	{Code: 403, Name: "Urban Railway Service", Category: "rail"},
	{Code: 404, Name: "All Urban Railway Services", Category: "rail"},
	{Code: 405, Name: "Monorail", Category: "rail"},
	{Code: 500, Name: "Metro Service", Category: "rail"},
	{Code: 600, Name: "Underground Service", Category: "rail"},
	{Code: 700, Name: "Bus Service", Category: "bus"},
	{Code: 701, Name: "Regional Bus Service", Category: "bus"},
	{Code: 702, Name: "Express Bus Service", Category: "bus"},
	{Code: 703, Name: "Stopping Bus Service", Category: "bus"},
	{Code: 704, Name: "Local Bus Service", Category: "bus"},
	{Code: 705, Name: "Night Bus Service", Category: "bus"},
	{Code: 706, Name: "Post Bus Service", Category: "bus"},
	{Code: 707, Name: "Special Needs Bus", Category: "bus"},
	{Code: 708, Name: "Mobility Bus Service", Category: "bus"},
	{Code: 709, Name: "Mobility Bus for Registered Disabled", Category: "bus"},
	{Code: 710, Name: "Sightseeing Bus", Category: "bus"},
	{Code: 711, Name: "Shuttle Bus", Category: "bus"},
	{Code: 712, Name: "School Bus", Category: "bus"},
	{Code: 713, Name: "School and Public Service Bus", Category: "bus"},
	{Code: 714, Name: "Rail Replacement Bus Service", Category: "bus"},
	{Code: 715, Name: "Demand and Response Bus Service", Category: "bus"},
	{Code: 716, Name: "All Bus Services", Category: "bus"},
	{Code: 800, Name: "Trolleybus Service", Category: "bus"},
	{Code: 900, Name: "Tram Service", Category: "rail"},
	{Code: 901, Name: "City Tram Service", Category: "rail"},
	{Code: 902, Name: "Local Tram Service", Category: "rail"},
	{Code: 903, Name: "Regional Tram Service", Category: "rail"},
	{Code: 904, Name: "Sightseeing Tram Service", Category: "rail"},
	{Code: 905, Name: "Shuttle Tram Service", Category: "rail"},
	{Code: 906, Name: "All Tram Services", Category: "rail"},
	{Code: 1000, Name: "Water Transport Service", Category: "water"},
	{Code: 1001, Name: "International Car Ferry Service", Category: "water"},
	{Code: 1002, Name: "National Car Ferry Service", Category: "water"},
	{Code: 1003, Name: "Regional Car Ferry Service", Category: "water"},
	{Code: 1004, Name: "Local Car Ferry Service", Category: "water"},
	{Code: 1005, Name: "International Passenger Ferry Service", Category: "water"},
	{Code: 1006, Name: "National Passenger Ferry Service", Category: "water"},
	{Code: 1007, Name: "Regional Passenger Ferry Service", Category: "water"},
	{Code: 1008, Name: "Local Passenger Ferry Service", Category: "water"},
	{Code: 1009, Name: "Post Boat Service", Category: "water"},
	{Code: 1010, Name: "Train Ferry Service", Category: "water"},
	{Code: 1011, Name: "Road-Link Ferry Service", Category: "water"},
	{Code: 1012, Name: "Airport-Link Ferry Service", Category: "water"},
	{Code: 1013, Name: "Car High-Speed Ferry Service", Category: "water"},
	{Code: 1014, Name: "Passenger High-Speed Ferry Service", Category: "water"},
	{Code: 1015, Name: "Sightseeing Boat Service", Category: "water"},
	{Code: 1016, Name: "School Boat", Category: "water"},
	{Code: 1017, Name: "Cable-Drawn Boat Service", Category: "water"},
	{Code: 1018, Name: "River Bus Service", Category: "water"},
	{Code: 1019, Name: "Scheduled Ferry Service", Category: "water"},
	{Code: 1020, Name: "Shuttle Ferry Service", Category: "water"},
	{Code: 1021, Name: "All Water Transport Services", Category: "water"},
	{Code: 1100, Name: "Air Service", Category: "air"},
	{Code: 1101, Name: "International Air Service", Category: "air"},
	{Code: 1102, Name: "Domestic Air Service", Category: "air"},
	{Code: 1103, Name: "Intercontinental Air Service", Category: "air"},
	{Code: 1104, Name: "Domestic Scheduled Air Service", Category: "air"},
	{Code: 1105, Name: "Shuttle Air Service", Category: "air"},
	{Code: 1106, Name: "Intercontinental Charter Air Service", Category: "air"},
	{Code: 1107, Name: "International Charter Air Service", Category: "air"},
	{Code: 1108, Name: "Round-Trip Charter Air Service", Category: "air"},
	{Code: 1109, Name: "Sightseeing Air Service", Category: "air"},
	{Code: 1110, Name: "Helicopter Air Service", Category: "air"},
	{Code: 1111, Name: "Domestic Charter Air Service", Category: "air"},
	{Code: 1112, Name: "Schengen-Area Air Service", Category: "air"},
	{Code: 1113, Name: "Airship Service", Category: "air"},
	{Code: 1114, Name: "All Air Services", Category: "air"},
	{Code: 1200, Name: "Ferry Service", Category: "water"},
	{Code: 1300, Name: "Telecabin Service", Category: "other"},
	{Code: 1301, Name: "Telecabin Service", Category: "other"},
	{Code: 1302, Name: "Cable Car Service", Category: "other"},
	{Code: 1303, Name: "Elevator Service", Category: "other"},
	{Code: 1304, Name: "Chair Lift Service", Category: "other"},
	{Code: 1305, Name: "Drag Lift Service", Category: "other"},
	{Code: 1306, Name: "Small Telecabin Service", Category: "other"},
	{Code: 1307, Name: "All Telecabin Services", Category: "other"},
	{Code: 1400, Name: "Funicular Service", Category: "other"},
	{Code: 1401, Name: "Funicular Service", Category: "other"},
	{Code: 1402, Name: "All Funicular Service", Category: "other"},
	{Code: 1500, Name: "Taxi Service", Category: "other"},
	{Code: 1501, Name: "Communal Taxi Service", Category: "other"},
	{Code: 1502, Name: "Water Taxi Service", Category: "other"},
	{Code: 1503, Name: "Rail Taxi Service", Category: "other"},
	{Code: 1504, Name: "Bike Taxi Service", Category: "other"},
	{Code: 1505, Name: "Licensed Taxi Service", Category: "other"},
	{Code: 1506, Name: "Private Hire Service Vehicle", Category: "other"},
	{Code: 1507, Name: "All Taxi Services", Category: "other"},
	{Code: 1600, Name: "Self Drive", Category: "other"},
	{Code: 1601, Name: "Hire Car", Category: "other"},
	{Code: 1602, Name: "Hire Van", Category: "other"},
	{Code: 1603, Name: "Hire Motorbike", Category: "other"},
	{Code: 1604, Name: "Hire Cycle", Category: "other"},
	{Code: 1700, Name: "Miscellaneous Service", Category: "other"},
	{Code: 1701, Name: "Cable Car", Category: "other"},
	{Code: 1702, Name: "Horse-drawn Carriag", Category: "other"},
}

func GetRouteType(code int) (RouteType, bool) {
	for _, i := range RouteTypes {
		if i.Code == code {
			return i, true
		}
	}
	return RouteType{}, false
}

func GetRouteCategory(category string) []RouteType {
	rt := []RouteType{}
	for _, i := range RouteTypes {
		if i.Category == category {
			rt = append(rt, i)
		}
	}
	return rt
}
